name: Download Racer Master

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install lhasa
        run: |
          sudo apt-get update
          sudo apt-get install -y lhasa

      - name: Download racer master
        run: |
          curl -L https://www.boatrace.jp/owpc/pc/extra/data/racer/LIST.LZH -o LIST.LZH

      - name: Extract LZH
        run: |
          lhasa -x LIST.LZH
          ls -la